### ISSUE TITLE
terraform timeout

### ISSUE THREAD

**Issue by nu0l** [selefra/TerraformGoat#98]
root@29d0dabbd376:/TerraformGoat/aliyun/oss/unrestricted_file_upload# terraform init

Initializing the backend...

Initializing provider plugins...
- Finding aliyun/alicloud versions matching "1.163.0"...
- Finding latest version of hashicorp/random...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider aliyun/alicloud: could not connect to registry.terraform.io: Failed to request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": dial tcp [2a04:4e42:1a::561]:443: connect: cannot assign requested address
╵

╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/random: could not query provider registry for registry.terraform.io/hashicorp/random: the request
│ failed after 2 attempts, please try again later: Get "https://registry.terraform.io/v1/providers/hashicorp/random/versions": net/http: request canceled while waiting for
│ connection (Client.Timeout exceeded while awaiting headers)

**Comment by teamssix** [comment]
看看容器有没有网，如果有网的话，可以看看能不能连通外网，如果不能连通外网的话，可以挂上代理再试试
